In [3]:
import numpy as np

In [2]:
conv = np.array([[1./16., 1./8., 1/16.],[1./8., 1./4., 1./8.],[1./16.,1./8.,1./16.]])

In [11]:
field = np.arange(0,9**2)
field = field.reshape(9,9)
N = (9+1)//2
field_restrict = np.zeros((N,N))

for i in range(N):
    for j in range(N):
        if i!=0 and i!=N-1 and j!=0 and j!=N-1:
            field_restrict[i,j] = (field[2*i-1:2*i+2,2*j-1:2*j+2]*conv).sum()
        else:
            field_restrict[i,j] = field[2*i,2*j]
field_restrict = field_restrict.reshape(-1,1)

In [12]:
field_restrict

array([[ 0.],
       [ 2.],
       [ 4.],
       [ 6.],
       [ 8.],
       [18.],
       [20.],
       [22.],
       [24.],
       [26.],
       [36.],
       [38.],
       [40.],
       [42.],
       [44.],
       [54.],
       [56.],
       [58.],
       [60.],
       [62.],
       [72.],
       [74.],
       [76.],
       [78.],
       [80.]])

In [13]:
field

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [4]:
33*33-1

1088

In [15]:
R = 0.25*np.array([[1,2,1,0,0,0,0],[0,0,1,2,1,0,0],[0,0,0,0,1,2,1]])
A = np.array([[2,-1,0,0,0,0,0],[-1,2,-1,0,0,0,0],[0,-1,2,-1,0,0,0],\
              [0,0,-1,2,-1,0,0],[0,0,0,-1,2,-1,0],[0,0,0,0,-1,2,-1],[0,0,0,0,0,-1,2]])
I = 2*R.T

In [16]:
R@A@I

array([[ 0.5 , -0.25,  0.  ],
       [-0.25,  0.5 , -0.25],
       [ 0.  , -0.25,  0.5 ]])