In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
A = np.array([[1,2],[5e-19,0.]])
np.linalg.inv(A)

array([[ 0.e+00,  2.e+18],
       [ 5.e-01, -1.e+18]])

In [2]:
def MAKE_POS_MATRIX(pos):
    x,y,z = pos[0], pos[1], pos[2]
    X = np.zeros((N,N))
    Y = np.zeros((N,N))
    Z = np.zeros((N,N))
    for i in range(N):
        X[i] = np.roll(x,-i)
        Y[i] = np.roll(y,-i)
        Z[i] = np.roll(z,-i)
    return np.vstack((np.expand_dims(X,axis=0),np.expand_dims(Y,axis=0),np.expand_dims(Z,axis=0)))

def MAKE_MASS_MATRIX(mass):
    M = np.zeros((N,N))
    for i in range(N):
        M[i] = np.roll(mass,-i)
    return M
        
def GET_ACCELERATION(X,M):
    pos = np.expand_dims(X[:,:,0],axis=2)
    return ((((X[:,:,1:]-pos)**2).sum(axis=0))**-1.5*M[:,1:]*(X[:,:,1:]-pos)).sum(axis=2)

def DKD_SCHEME(pos,vel,M,dt):
    pos += vel*0.5*dt
    X = MAKE_POS_MATRIX(pos)
    A = GET_ACCELERATION(X,M)
    vel += A*dt
    pos += vel*0.5*dt
    return pos, vel

def KDK_SCHEME(pos,vel,M,A,dt):
    vel += A*0.5*dt
    pos += vel*dt
    X = MAKE_POS_MATRIX(pos)
    A = GET_ACCELERATION(X,M)
    vel += A*0.5*dt
    return pos, vel, A

In [15]:
N = 3
x = np.array([0.0, -3**0.5/2., 3**0.5/2.])
y = np.array([1., -0.5, -0.5])
z = np.array([0.0, 0.0, 0.0])
# x = np.random.normal(loc=5.0, scale=16., size=N)
# y = np.random.normal(loc=-4.0, scale=8., size=N)
# z = np.random.normal(loc=2.2, scale=4., size=N)
pos = np.vstack((x,y,z))
vx = np.array([-1./3**0.25,1./3**0.25*0.5,1./3**0.25*0.5])
vy = np.array([0.0,-1./3**0.25*3**0.5/2., 1./3**0.25*3**0.5/2.])
vz = np.array([0.0,0.0, 0.0])
# vx = np.random.normal(loc=0.3, scale=2., size=N)
# vy = np.random.normal(loc=-0.1, scale=1.5, size=N)
# vz = np.random.normal(loc=-0.45, scale=1.6, size=N)
mass = np.array([1.0, 1.0, 1.0])
# mass = 10.*np.random.uniform(size=N)
vel = np.vstack((vx,vy,vz))
M = MAKE_MASS_MATRIX(mass)

In [92]:
N = 3
x = np.array([0.0, -3**0.5/2., 3**0.5/2.])
y = np.array([1., -0.5, -0.5])
z = np.array([0.0, 0.0, 0.0])
# x = np.random.normal(loc=5.0, scale=16., size=N)
# y = np.random.normal(loc=-4.0, scale=8., size=N)
# z = np.random.normal(loc=2.2, scale=4., size=N)
pos = np.vstack((x,y,z))
vx = np.array([-1./3**0.25,1./3**0.25*0.5,1./3**0.25*0.5])
vy = np.array([0.0,-1./3**0.25*3**0.5/2., 1./3**0.25*3**0.5/2.])
vz = np.array([0.0,0.0, 0.0])
# vx = np.random.normal(loc=0.3, scale=2., size=N)
# vy = np.random.normal(loc=-0.1, scale=1.5, size=N)
# vz = np.random.normal(loc=-0.45, scale=1.6, size=N)
mass = np.array([1.0, 1.0, 1.0])
# mass = 10.*np.random.uniform(size=N)
vel = np.vstack((vx,vy,vz))
M = MAKE_MASS_MATRIX(mass)

dt = 1e-2
t = 0.0
end_t = 50.
mode = 'DKD'

if mode == 'KDK':
    X = MAKE_POS_MATRIX(pos)
    acc = GET_ACCELERATION(X,M)
    while t<end_t:
        pos, vel, acc = KDK_SCHEME(pos,vel,M,acc,dt)
        t += dt
elif mode == 'DKD':
    while t<end_t:
        pos, vel = DKD_SCHEME(pos,vel,M,dt)
        t += dt

In [93]:
theta = np.pi/2 + np.arange(3)*np.pi*2/3
theta += 1./3**0.25*t
x_analytic = np.cos(theta)
y_analytic = np.sin(theta)
print(x_analytic)
print(y_analytic)
vx_analytic = 1./3**0.25*np.cos(theta+np.pi/2)
vy_analytic = 1./3**0.25*np.sin(theta+np.pi/2)
print(vx_analytic)
print(vy_analytic)

[-0.2957789  -0.67938689  0.97516578]
[ 0.95525643 -0.73378025 -0.22147618]
[-0.72583792  0.55755242  0.1682855 ]
[-0.22474336 -0.5162224   0.74096576]


In [94]:
print(pos)
print(vel)

[[-0.2951933  -0.67982622  0.97501952]
 [ 0.95551739 -0.73321505 -0.22230234]
 [ 0.          0.          0.        ]]
[[-0.72605984  0.55722629  0.16883356]
 [-0.22418936 -0.5165903   0.74077966]
 [ 0.          0.          0.        ]]


In [95]:
theta

array([39.57017897, 41.66457407, 43.75896917])

In [62]:
0.265**2+0.96**2

0.991825

In [24]:
1/(2**2*3)*1/3**0.5*2

0.09622504486493763